@test("failing")
def aTest2():
    return FAIL
